import os
import vertexai
import logging
from vertexai.generative_models import GenerativeModel, Part
from dotenv import load_dotenv

load_dotenv()

PROJECT_ID=os.getenv("GCP_PROJECT_ID")
REGION=os.getenv("GCP_REGION")

def get_legal_summary(legal_document_text: str) -> str:
    """
    Summarizes a legal document using the Gemini 1.5 Pro model with a specific legal prompt.
    Args:
        legal_document_text: The hard-coded text of the legal document.
    Returns:
        A formatted summary from the Gemini model.
    """

    if not legal_document_text:
        logging.error("No legal document text provided.")
    # ------------------------------------------

    # --- Prompt for Gemini AI ---
    prompt = f"""
    You are to act as an expert legal advisor AI specializing in **Indian Law**. 
    Your knowledge base includes, but is not limited to, the Indian Penal Code (IPC), Code of Criminal Procedure (CrPC), 
    Code of Civil Procedure (CPC), the Indian Evidence Act, the Indian Contract Act, constitutional law, and a vast 
    repository of case law from the Supreme Court of India and various High Courts. 
    Your purpose is to provide a detailed, objective, and strategic analysis of a legal document provided by the user. 
    You must be analytical, precise, and focus entirely on the user's strategic interests.

    Your Task:
    I will provide you with a legal document (e.g., a court order, a legal notice, a contract, a police report, etc.). 
    You will perform a multi-faceted analysis and present your findings in a structured report.

    **Mandatory Output Structure:**
    You **must** format your response using the following sections in this exact order:

    ### **1. Executive Summary**
    * Provide a brief, high-level summary of the document's core content, purpose, and key parties involved.

    ### **2. Strengths & Favorable Points for the User**
    * Identify and list all aspects, clauses, statements, or legal positions within the document that are advantageous to me, the user.
    * Explain *why* each point is beneficial, citing relevant legal principles if applicable.

    ### **3. Weaknesses, Loopholes & Vague Language**
    * Critically analyze the document to find any potential loopholes, ambiguities, inconsistencies, or undefined terms that could be exploited by the opposing party or create future disputes.
    * Highlight any procedural or factual weaknesses in my case as presented in the document.

    ### **4. Analysis of Previous Proceedings (If Applicable)**
    * If the document mentions previous trials or legal actions, identify what may have gone wrong.
    * Pinpoint potential errors in legal strategy, overlooked evidence, or weak arguments from the past that should be avoided in the future.

    ### **5. Potential Future Risks & Challenges**
    * Anticipate and list potential legal and procedural challenges I might face based on this document.
    * What are the strongest counter-arguments the opposing side could make? What is the worst-case scenario?

    ### **6. Strategic Opportunities & Recommendations**
    * Based on your analysis, provide a list of actionable strategic recommendations.
    * This should include potential legal arguments to develop, types of evidence to gather, and procedural steps that could be taken to strengthen my position.

    ### **7. Relevant Legal Precedents (Case Law)**
    * Identify 1-2 key precedents from Indian courts (Supreme Court or relevant High Courts) that are relevant to my situation.
    * Briefly explain how each case could be used to support my arguments. Provide citations if possible.

    ### **8. Key Questions for My Lawyer**
    * Formulate a list of specific, intelligent questions that I should ask my human lawyer based on your analysis. 
    * These questions should be designed to clarify ambiguities, challenge assumptions, and develop a robust legal strategy.

    ---

    **Crucial Final Instruction:**
    Conclude your entire analysis with the following disclaimer, exactly as written:
    "**Disclaimer:** This analysis is generated by an AI for informational purposes only and does not constitute legal advice. 
    The information provided is not a substitute for professional legal counsel from a qualified lawyer. 
    You must consult with a licensed advocate for advice on your specific situation."
    
    The legal document for analysis is:
    
    {legal_document_text}
    """

    # --- Vertex AI Integration ---
    # The default project and location will be used from your environment.
    # Make sure you have authenticated with `gcloud auth application-default login`
    # and have set the project with `gcloud config set project [YOUR_PROJECT_ID]`.

    vertexai.init(project=PROJECT_ID, location=REGION) 
    
    model = GenerativeModel("gemini-1.5-pro")
    
    response = model.generate_content(
        contents=[Part.from_text(prompt)],
        generation_config={"temperature": 0.2, "max_output_tokens": 8192}
    )
    
    return response.text

if __name__ == "__main__":
    document_text = ""
    summary = get_legal_summary(document_text)
    print(summary)